/*----------------------------------------------------------------------------
 * 
 ---------------------------------------------------------------------------*/
public class ContractPartyCreationAPI {
	
    //Variable declaration
    public static string finalResponse;
    
    //Method to call contract party creation API to send account details as Input
    //Contract number will be response.
    public static string contractPartyCreationCallout(){
        try{
            
        }
        catch(Exception e){
            
        }
        return null;
    }
    
    //Generate JSON request from account object.
    public static string JSONGenerateRequest(){
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        return null;
    }
}