public class FieldDetailWrapper{
        @AuraEnabled 
        public String fieldName;
        @AuraEnabled  
        public String displayName;
        @AuraEnabled
        public String dataType;
        @AuraEnabled
        public String length;
        @AuraEnabled
        public String mandatory;
        @AuraEnabled
        public String allowedValues;
        @AuraEnabled
        public String defaultValue;
        @AuraEnabled
        public String applicableModules;
        @AuraEnabled
        public String contractRelationship;
        @AuraEnabled
        public String mappingField1;
        @AuraEnabled
        public String mappingField2;
        @AuraEnabled
        public String firstObject;
        @AuraEnabled
        public String secondObject;
        @AuraEnabled
        public Boolean isSelected;
        @AuraEnabled
        public String contractType;
        @AuraEnabled
        public String contractSubType;

}