public class LineItemMetaDataResponseJson{
	public cls_IntegrationEntities IntegrationEntities;
	class cls_IntegrationEntities {
		public cls_integrationEntity[] integrationEntity;
	}
	class cls_integrationEntity {
		public cls_integrationEntityHeader integrationEntityHeader;
		public cls_integrationEntityDetails integrationEntityDetails;
	}
	class cls_integrationEntityHeader {
		public String integrationTrackingNumber;	//INTEGRATIONTRACKINGNUMBER
		public String referenceCodeForEntity;	//
		public String additionalInfo;	//ADDITIONALINFO
	}
	class cls_integrationEntityDetails {
		public cls_metadata metadata;
	}
	class cls_metadata {
		public cls_contractMetadata contractMetadata;
		public cls_lineItemMetadata lineItemMetadata;
	}
	class cls_contractMetadata {
		public cls_metadataDetails[] metadataDetails;
	}
	class cls_metadataDetails {
		public String type;	//Procurement
		public String subType;	//Purchase
		public cls_fieldMetadata fieldMetadata;
	}
	class cls_fieldMetadata {
		public cls_fieldDetails[] fieldDetails;
	}
	class cls_fieldDetails {
		public String fieldName;	//itemNumber
		public String displayName;	//Item Number
		public String dataType;	//String
		public String length;	//255
		public String mandatory;	//YES
		public String allowedValues;	//
		public String defaultValue;	//
		public String applicableModules;	//Repository,Authoring
		public String lineItemRelationship;	//ONE-ONE
	}
	class cls_subFields {
		public cls_subField[] subField;
	}
	class cls_subField {
		public String fieldName;	//
		public String displayName;	//
		public String dataType;	//
		public String length;	//
		public String mandatory;	//
		public String allowedValues;	//
		public String defaultValue;	//
	}
	class cls_lineItemMetadata {
		public cls_fieldDetails[] fieldDetails;
	}
	public static LineItemMetaDataResponseJson parse(String json){
		return (LineItemMetaDataResponseJson) System.JSON.deserialize(json, LineItemMetaDataResponseJson.class);
	}

}